ARG CRYSTAL_VERSION=1.1.1
FROM crystallang/crystal:${CRYSTAL_VERSION}-alpine
WORKDIR /app

RUN apk add --no-cache bash
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing watchexec

COPY entrypoint.sh /app/entrypoint.sh

COPY shard.yml /app
COPY shard.override.yml /app
COPY shard.lock /app
RUN shards install --ignore-crystal-version

COPY spec /app/spec
COPY src /app/src

CMD /app/entrypoint.sh
