version: "3.7"

services:
  db:
    hostname: staff_api_db
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: staff_api_test
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
    ports:
      - 5432:5432

  test:
    hostname: staff_api
    build:
      context: ./
      dockerfile: Dockerfile.test
      args:
        CRYSTAL_VERSION: ${CRYSTAL_VERSION:-latest}
    depends_on:
      - db
    volumes:
      - ./spec:/app/spec
      - ./src:/app/src
    environment:
      PG_DATABASE_URL: postgresql://postgres:password@db:5432/staff_api_test
      PLACE_URI: http://toby.dev.place.tech
      PLACE_EMAIL: toby@place.technology.com
      PLACE_PASSWORD: password
      PLACE_AUTH_CLIENT_ID: abc123
      PLACE_AUTH_SECRET: abc123
      GITHUB_ACTION: ${GITHUB_ACTION-}
