#! /usr/bin/env bash

set -eu

# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{
    docker compose down &> /dev/null
    exit 2
}

# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

docker compose pull -q

docker compose build -q

exit_code="0"

tty_flag=""
if [ ! -t 0 ]; then
    tty_flag="-T"
fi

docker compose run --rm $tty_flag test $@ || exit_code="$?"

docker compose down &> /dev/null

exit ${exit_code}
