name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Sunday at midnight
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/install-crystal@v1
      - uses: actions/checkout@v2
      - name: Crystal Format
        run: crystal tool format --check
      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: "crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.1.1
          - latest
        include:
          - crystal: nightly
            stable: false
    continue-on-error: ${{ !matrix.stable }}
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose test environment
        run: ./test
        env:
          CRYSTAL_VERSION: ${{ matrix.crystal }}
